[package]
name = "SimpleToken"
version = "1.0.0"
authors = []

[addresses]
aptos_token = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
aptos_token = "0x1"
